FROM python:3.13-slim-bookworm AS packagepython

ARG GRB_VERSION=13.0.0b1

LABEL vendor="Gurobi"
LABEL version=${GRB_VERSION}

# update system and certificates
# RUN sed -i 's|http://deb.debian.org|http://ftp.de.debian.org|g' /etc/apt/sources.list \
RUN apt-get update \
    && apt-get install --no-install-recommends -y\
       ca-certificates  \
       p7zip-full \
       zip \
    && update-ca-certificates \
    && python -m pip install gurobipy==${GRB_VERSION} \
    && rm -rf /var/lib/apt/lists/*